name: ruz-test

on:
  workflow_dispatch:
    inputs:
      years:
        description: "Last N years"
        required: true
        default: "5"
      rps:
        description: "Global requests/sec cap"
        required: true
        default: "10"
      shard:
        description: "This shard id (0-based)"
        required: true
        default: "0"
      of:
        description: "Total shards"
        required: true
        default: "1"
      rotate_mb:
        description: "Rotate chunk size MB"
        required: true
        default: "32"
      concurrency:
        description: "Worker threads"
        required: true
        default: "32"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run shard
        run: |
          mkdir -p out
          python ruz_bulk_local.py \
            --years "${{ inputs.years }}" \
            --base-dir out \
            --concurrency "${{ inputs.concurrency }}" \
            --rps "${{ inputs.rps }}" \
            --report-every 30 \
            --rotate-mb "${{ inputs.rotate_mb }}" \
            --codec zstd \
            --shard "${{ inputs.shard }}" \
            --of "${{ inputs.of }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruz-shard-${{ inputs.shard }}
          path: out/**
          if-no-files-found: error
