name: ruz-bulk
on:
  workflow_dispatch:
    inputs:
      years:       { description: "Years",       required: true,  default: "5",  type: string }
      rps:         { description: "Global RPS",  required: true,  default: "10", type: string }
      shard:       { description: "Shard id",    required: true,  default: "1",  type: string }
      of:          { description: "Total shards",required: true,  default: "16", type: string }
      rotate_mb:   { description: "Rotate MB",   required: true,  default: "128",type: string }
      concurrency: { description: "Threads",     required: true,  default: "64", type: string }

jobs:
  run-shard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests zstandard
      - name: Run shard
        env:
          YEARS:       ${{ inputs.years }}
          RPS:         ${{ inputs.rps }}
          SHARD:       ${{ inputs.shard }}
          OF:          ${{ inputs.of }}
          ROTATE_MB:   ${{ inputs.rotate_mb }}
          CONCURRENCY: ${{ inputs.concurrency }}
        run: |
          mkdir -p out
          python ruz_bulk_local.py \
            --years "$YEARS" \
            --base-dir out \
            --concurrency "$CONCURRENCY" \
            --rps "$RPS" \
            --report-every 60 \
            --rotate-mb "$ROTATE_MB" \
            --shard "$SHARD" --of "$OF"
      - name: Upload artifact (all types for this shard)
        uses: actions/upload-artifact@v4
        with:
          name: ruz-shard-${{ inputs.shard }}
          path: out/**
          retention-days: 5
