name: ruz-bulk

on:
  workflow_dispatch:
    inputs:
      years:        { description: "Years",        required: true,  default: "30",  type: string }
      rps:          { description: "Global RPS",   required: true,  default: "10",  type: string }
      shard:        { description: "Shard id",     required: true,  default: "1",   type: string }
      of:           { description: "Total shards", required: true,  default: "16",  type: string }
      rotate_mb:    { description: "Rotate MB",    required: true,  default: "128", type: string }
      concurrency:  { description: "Threads",      required: true,  default: "64",  type: string }
      min_year:     { description: "Min year (inclusive)", required: false, default: "1995", type: string }
      max_year:     { description: "Max year (inclusive)", required: false, default: "2012", type: string }

jobs:
  run-shard:
    runs-on: ubuntu-latest
    timeout-minutes: 300 # hard cap: 5 hours

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests zstandard

      - name: Run shard (soft stop before 5h)
        env:
          YEARS:        ${{ inputs.years }}
          RPS:          ${{ inputs.rps }}
          SHARD:        ${{ inputs.shard }}
          OF:           ${{ inputs.of }}
          ROTATE_MB:    ${{ inputs.rotate_mb }}
          CONCURRENCY:  ${{ inputs.concurrency }}
          MIN_YEAR:     ${{ inputs.min_year }}
          MAX_YEAR:     ${{ inputs.max_year }}
          PYTHONUNBUFFERED: "1"
        run: |
          mkdir -p out
          # Soft limit to allow artifact upload even if still working near the hard cap.
          # 4h55m = 17,700 seconds
          timeout --signal=INT --kill-after=30s 17700s \
          python ruz_bulk_local.py \
            --years "$YEARS" \
            --base-dir out \
            --concurrency "$CONCURRENCY" \
            --rps "$RPS" \
            --report-every 60 \
            --rotate-mb "$ROTATE_MB" \
            --shard "$SHARD" --of "$OF" \
            --min-year "$MIN_YEAR" --max-year "$MAX_YEAR" \
          || true

      - name: Upload artifact (all types for this shard)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ruz-shard-${{ inputs.shard }}
          path: out/**
          retention-days: 5
