on:
  workflow_dispatch:
    inputs:
      years:
        description: "Legacy input; ignored if min_year/max_year are set"
        required: false
        default: "30"
      shard:
        description: "Shard number"
        required: true
      of:
        description: "Total shards"
        required: true
        default: "48"
      rps:
        description: "Requests per second"
        required: false
        default: "30"
      rotate_mb:
        description: "Rotate artifact at ~MB"
        required: false
        default: "64"
      concurrency:
        description: "Downloader concurrency"
        required: false
        default: "64"
      min_year:
        description: "Lower bound year (inclusive)"
        required: false
        default: ""
      max_year:
        description: "Upper bound year (inclusive)"
        required: false
        default: ""

jobs:
  ruz-bulk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r tools/requirements.txt
      - name: Run bulk
        env:
          SHARD:        ${{ github.event.inputs.shard }}
          OF:           ${{ github.event.inputs.of }}
          RPS:          ${{ github.event.inputs.rps }}
          ROTATE_MB:    ${{ github.event.inputs.rotate_mb }}
          CONC:         ${{ github.event.inputs.concurrency }}
          MIN_YEAR:     ${{ github.event.inputs.min_year }}
          MAX_YEAR:     ${{ github.event.inputs.max_year }}
        run: |
          python tools/ruz_bulk_runner.py \
            --shard "$SHARD" --of "$OF" --rps "$RPS" --concurrency "$CONC" --rotate-mb "$ROTATE_MB" \
            ${MIN_YEAR:+--min-year "$MIN_YEAR"} \
            ${MAX_YEAR:+--max-year "$MAX_YEAR"}
